//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Admin
    {
        public int ID { get; set; }
        [Display(Name="Admin Name")]
        [Required(ErrorMessage ="Please Enter Admin Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Admin Password")]
        public string Password { get; set; }
        [Display(Name ="Control Type")]
        public int Type { get; set; }
    }
}
