//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career_Requirment
    {
        public int ID { get; set; }
        public Nullable<int> Reqirment_ID { get; set; }
        public Nullable<int> Career_ID { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Requirment Requirment { get; set; }
    }
}
