//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.Content_Details = new HashSet<Content_Details>();
        }
    
        public int ID { get; set; }
        [Display(Name="C-Solution Name")]
        [Required(ErrorMessage ="Please Enter Content Solution Name")]
        public string Name { get; set; }
        [Display(Name = "C-Solution Description")]
        [Required(ErrorMessage = "Please Enter Content Solution Description")]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content_Details> Content_Details { get; set; }
    }
}
