//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Custom_Price()
        {
            this.custom_videos = new HashSet<custom_videos>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfDeadLine { get; set; }
        public string Message { get; set; }
        public string Contact { get; set; }
        public string Other { get; set; }
        public int UsersID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<custom_videos> custom_videos { get; set; }
        public virtual User User { get; set; }
    }
}
