//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Orders
    {
        public int ID { get; set; }
        public int PricingId { get; set; }
        public int UsersID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Pricing Pricing { get; set; }
        public virtual User User { get; set; }
    }
}
