//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Protoflio
    {
        public int ID { get; set; }
        [Display(Name ="Portfolio Name")]
        [Required(ErrorMessage ="Please Enter Portfolio Name")]
        public string Name { get; set; }
    }
}
