//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Gate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Team
    {
        public int ID { get; set; }
        [Required(ErrorMessage="Please Enter Name ")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Job ")]
        public string Job { get; set; }
        [Required(ErrorMessage = "Please Enter Facebook URL ")]
        public string Facebook { get; set; }
        [Required(ErrorMessage = "Please Enter Twitter URL ")]
        public string Twitter { get; set; }
        [Required(ErrorMessage = "Please Enter Instgram URL ")]
        public string Instgram { get; set; }
    }
}
